### ISSUE TITLE
Unbalanced training

### ISSUE THREAD

**Issue by dashaub** [xeneta/LeadQualifier#1]
Since you probably would rather include companies that the model can't clearly classify in the list of sales leads (i.e. adjusting your type I vs type II error tolerance), you could employ an unbalanced training set. Of course you could also reach deeper into the scored probabilities, but it is an empirical question as to which approach would work better on your data.

**Comment by perborgen** [comment]
Good point. We will not be doing this now, but feel free to submit a pull request if you'd like to do this yourself.
