### ISSUE TITLE
Better performance evaluation

### ISSUE THREAD

**Issue by halflings** [xeneta/LeadQualifier#7]
It would be nice to give the precision and recall of your algorithm instead of only giving the accuracy: Your algorithm my have a low recall but high precision (accuracy), which wouldn't make it as useful as another model which makes slightly more mistakes, but overall finds a significantly higher number of leads.
If you want to qualify this by using one metric alone, you can use the area under the ROC curve.

**Comment by perborgen** [comment]
Thanks for the input and tip! 

I have considered this, and after testing on a real world dataset lately, the precision was significantly lower than the recall. So it definitely needs to be addressed.

I'll fix it when I have time.

**Comment by perborgen** [comment]
Hey, I've added precision, recall and f1 score to the README and the xeneta_qualifier (the new script where we welcome people to add their own algorithms) and to the train_algorithm script, so I'm closing this one.

**Comment by halflings** [comment]
Prefect. Thanks Per!
