### ISSUE TITLE
While training algorithm, missing conditional?

### ISSUE THREAD

**Issue by iamdavidmartin** [xeneta/LeadQualifier#8]
Hi there,

First, thank you for creating this and explaining how it works! It's had a huge benefit for me.

On line 28 of https://github.com/xeneta/LeadQualifier/blob/master/train_algorithm/run.py you define:

`def cleanUp(descriptions, disc=False):`

But I can't find where `disc` is used. You call `cleanUp` later on with it set as `True;`

`disqualified_clean_descriptions = cleanUp(..., True)`

I might be missing something but I want to make sure my model (and yours) is trained really well. Is there an option that was set in a version at one point but then fell out? I can't find it used in the git history either.

Thank you again for your work.

David

**Comment by perborgen** [comment]
Sorry for the late reply, you're absolutely right, that's an unnecessary argument. Removing it now.
