### ISSUE TITLE
csv requirement can't be satisfied with python3 (OSX)

### ISSUE THREAD

**Issue by aseidlitz** [xeneta/LeadQualifier#9]
csv requirement can't be satisfied with python3 (OSX)

Collecting csv (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement csv (from -r requirements.txt (line 6)) (from versions: )
No matching distribution found for csv (from -r requirements.txt (line 6))

Commenting out CSV resolves the issue

**Comment by perborgen** [comment]
Thanks for notifying us about this, we'll add it to the README
